import type { STXComponentType, STXNode } from './ir'

const COMPONENT_MAPPING: Record<string, STXComponentType> = {
  view: 'View',
  text: 'Text',
  button: 'Button',
  image: 'Image',
  img: 'Image',
  input: 'TextInput',
  textarea: 'TextInput',
  scroll: 'ScrollView',
  scrollview: 'ScrollView',
  list: 'FlatList',
  flatlist: 'FlatList',
  modal: 'Modal',
  switch: 'Switch',
  slider: 'Slider',
  picker: 'Picker',
  select: 'Picker',
  loading: 'ActivityIndicator',
  spinner: 'ActivityIndicator',
  div: 'View',
  span: 'Text',
  p: 'Text',
  h1: 'Text',
  h2: 'Text',
  h3: 'Text',
  h4: 'Text',
  h5: 'Text',
  h6: 'Text',
  a: 'TouchableOpacity',
  section: 'View',
  article: 'View',
  header: 'SafeAreaView',
  footer: 'View',
  main: 'View',
  nav: 'View',
  aside: 'View',
  form: 'View',
  label: 'Text',
  fieldset: 'View',
  legend: 'Text',
  option: 'Text',
  dialog: 'Modal',
  figure: 'View',
  figcaption: 'Text',
  picture: 'View',
  hr: 'View',
  ul: 'View',
  ol: 'View',
  li: 'View',
  dl: 'View',
  dt: 'Text',
  dd: 'Text',
  table: 'View',
  thead: 'View',
  tbody: 'View',
  tfoot: 'View',
  tr: 'View',
  th: 'Text',
  td: 'Text',
  caption: 'Text',
  strong: 'Text',
  b: 'Text',
  em: 'Text',
  i: 'Text',
  u: 'Text',
  s: 'Text',
  small: 'Text',
  mark: 'Text',
  abbr: 'Text',
  time: 'Text',
  code: 'Text',
  kbd: 'Text',
  samp: 'Text',
  pre: 'Text',
  blockquote: 'Text',
  cite: 'Text',
  q: 'Text',
  sub: 'Text',
  sup: 'Text',
}

/** Map rendered HTML and primitive tags to the native IR vocabulary. */
export function mapToNativeComponent(tag: string): STXComponentType | string {
  return COMPONENT_MAPPING[tag.toLowerCase()] || tag
}

/** Transform a node tree to use native component types. */
export function transformToNativeComponents(node: STXNode): STXNode {
  return {
    ...node,
    type: mapToNativeComponent(node.type),
    children: node.children.map(child => typeof child === 'string' ? child : transformToNativeComponents(child)),
  }
}
