/**
 * DOM-runtime shim for driving the signals runtime in tests.
 *
 * The client signals runtime (generated by `generateSignalsRuntime[Dev]`)
 * is written against real-browser DOM semantics. `very-happy-dom` (our
 * test DOM) diverges in two ways that make `processElement` un-runnable in
 * a plain unit test:
 *
 *   1. `Node.ELEMENT_NODE` / `TEXT_NODE` / etc. are `undefined`. The runtime
 *      gates on `el.nodeType !== Node.ELEMENT_NODE`, so with the constant
 *      undefined every element fails the guard and processElement bails.
 *   2. `el.attributes` is a `Map`, not a `NamedNodeMap`. The runtime does
 *      `Array.from(el.attributes).forEach(attr => attr.name…)`; on a Map
 *      that yields `[key, value]` pairs, so `attr.name` is `undefined` and
 *      the attribute loop throws `name.startsWith is not a function`.
 *
 * Both are environment gaps (a real browser defines `Node.ELEMENT_NODE = 1`
 * and exposes `attributes` as a NamedNodeMap). This shim closes them so the
 * runtime can be exercised behaviorally. Discovered while investigating
 * stacksjs/stx#1737; before this, every signals test was string-match only
 * because the runtime couldn't be driven against happy-dom.
 *
 * Usage:
 *   import { installNodeConstants, shimAttributes } from '../../test-utils/dom-runtime-shim'
 *   installNodeConstants()                     // once, before running the runtime
 *   new Function(generateSignalsRuntimeDev())()
 *   document.body.innerHTML = '…'
 *   shimAttributes(document.body)               // after each innerHTML assignment
 *   document.dispatchEvent(new window.Event('DOMContentLoaded'))
 */

/** Define the standard Node.nodeType constants happy-dom omits. Idempotent. */
export function installNodeConstants(): void {
  // eslint-disable-next-line ts/no-explicit-any
  const N: any = (globalThis as any).Node || ((globalThis as any).Node = {})
  if (N.ELEMENT_NODE == null)
    N.ELEMENT_NODE = 1
  if (N.TEXT_NODE == null)
    N.TEXT_NODE = 3
  if (N.COMMENT_NODE == null)
    N.COMMENT_NODE = 8
  if (N.DOCUMENT_NODE == null)
    N.DOCUMENT_NODE = 9
  if (N.DOCUMENT_FRAGMENT_NODE == null)
    N.DOCUMENT_FRAGMENT_NODE = 11
}

/**
 * Replace each element's `attributes` Map with a NamedNodeMap-shaped accessor:
 * array-like of `{ name, value }` (so `Array.from(el.attributes)` works the
 * way the runtime expects) while still delegating `get` / `set` / `delete` /
 * `has` / `keys` / `values` / `entries` / `forEach` / `size` to the backing
 * Map, so very-happy-dom's own `getAttribute` / `setAttribute` keep working.
 *
 * Walk root + all descendants; call again after inserting new markup. Each
 * element is shimmed once (guarded by `__attrShimmed`).
 */
// eslint-disable-next-line ts/no-explicit-any
export function shimAttributes(root: any): void {
  // eslint-disable-next-line ts/no-explicit-any
  const els: any[] = [root, ...Array.from(root.querySelectorAll('*'))]
  for (const el of els) {
    if (!el || el.nodeType !== 1 || el.__attrShimmed)
      continue
    const map: Map<string, string> = el.attributes
    if (!(map instanceof Map))
      continue
    el.__attrMap = map
    Object.defineProperty(el, 'attributes', {
      configurable: true,
      get() {
        const m: Map<string, string> = el.__attrMap
        // eslint-disable-next-line ts/no-explicit-any
        const arr: any = []
        let i = 0
        for (const [name, value] of m) arr[i++] = { name, value }
        arr.length = i
        arr.get = (k: string) => m.get(k)
        arr.set = (k: string, v: string) => m.set(k, v)
        arr.delete = (k: string) => m.delete(k)
        arr.has = (k: string) => m.has(k)
        arr.keys = () => m.keys()
        arr.values = () => m.values()
        arr.entries = () => m.entries()
        // eslint-disable-next-line ts/no-explicit-any
        arr.forEach = (cb: any) => m.forEach(cb)
        Object.defineProperty(arr, 'size', { get: () => m.size })
        arr.item = (n: number) => arr[n] || null
        arr.getNamedItem = (k: string) => (m.has(k) ? { name: k, value: m.get(k) } : null)
        return arr
      },
    })
    el.__attrShimmed = true
  }
}
