export type { AuthConfig, OAuthProviderConfig, Permission, Session, User } from './types'
export { createSession, destroySession, getSession, isSessionValid } from './session'
export { hashPassword, verifyPassword } from './password'
export { getUser, login, logout, register } from './auth'
export { can, definePermissions } from './permissions'
export { authMiddleware, guestMiddleware } from './middleware'
export type { MiddlewareResult } from './middleware'
export { handleOAuthCallback, oauthRedirectUrl } from './oauth'
