import { describe, expect, it } from 'bun:test'
import {
  extractTypesFromTemplate,
  generateTypeDefinitions,
} from '../../src/typescript-templates'

describe('generateTypeDefinitions', () => {
  it('should generate .d.ts file content', () => {
    const template = `
      @types
      interface PageContext {
        title: string
        items: number[]
      }
      @endtypes
    `
    const extracted = extractTypesFromTemplate(template)
    const result = generateTypeDefinitions('pages/home.stx', extracted)

    expect(result.filename).toBe('pages/home.d.ts')
    expect(result.content).toContain('// Auto-generated by stx')
    expect(result.content).toContain('Source: pages/home.stx')
  })

  it('should include interface definitions', () => {
    const template = `
      @types
      interface PageContext {
        title: string
        count: number
      }
      @endtypes
    `
    const extracted = extractTypesFromTemplate(template)
    const result = generateTypeDefinitions('test.stx', extracted)

    expect(result.content).toContain('export interface PageContext')
    expect(result.content).toContain('title: string')
    expect(result.content).toContain('count: number')
  })

  it('should include optional properties', () => {
    const template = `
      @types
      interface PageContext {
        required: string
        optional?: number
      }
      @endtypes
    `
    const extracted = extractTypesFromTemplate(template)
    const result = generateTypeDefinitions('test.stx', extracted)

    expect(result.content).toContain('required: string')
    expect(result.content).toContain('optional?: number')
  })

  it('should include readonly properties', () => {
    const template = `
      @types
      interface PageContext {
        readonly id: number
      }
      @endtypes
    `
    const extracted = extractTypesFromTemplate(template)
    const result = generateTypeDefinitions('test.stx', extracted)

    expect(result.content).toContain('readonly id: number')
  })

  it('should include type aliases', () => {
    const template = `
      @types
      type Status = 'active' | 'inactive'
      interface PageContext {
        status: Status
      }
      @endtypes
    `
    const extracted = extractTypesFromTemplate(template)
    const result = generateTypeDefinitions('test.stx', extracted)

    expect(result.content).toContain('export type Status')
  })

  it('should include typed render function', () => {
    const template = `
      @types
      interface PageContext {
        title: string
      }
      @endtypes
    `
    const extracted = extractTypesFromTemplate(template)
    const result = generateTypeDefinitions('test.stx', extracted)

    expect(result.content).toContain('export function render(context: PageContext): Promise<string>')
  })

  it('should use generic render type when no context', () => {
    const template = '<div>Hello</div>'
    const extracted = extractTypesFromTemplate(template)
    const result = generateTypeDefinitions('test.stx', extracted)

    expect(result.content).toContain('render(context: Record<string, unknown>)')
  })

  it('should handle complex nested types', () => {
    const template = `
      @types
      interface PageContext {
        user: { name: string; profile: { bio: string } }
        items: Array<{ id: number; label: string }>
      }
      @endtypes
    `
    const extracted = extractTypesFromTemplate(template)
    const result = generateTypeDefinitions('test.stx', extracted)

    expect(result.content).toContain('PageContext')
    expect(result.content).toContain('name: string')
  })

  it('should wrap in module declaration', () => {
    const template = `
      @types
      interface PageContext { x: number }
      @endtypes
    `
    const extracted = extractTypesFromTemplate(template)
    const result = generateTypeDefinitions('test.stx', extracted)

    expect(result.content).toContain('declare module "*.stx"')
    expect(result.content).toContain('}')
  })
})
