name: Buddy
options:
  bundleIdPrefix: com.stacksjs
  deploymentTarget:
    iOS: "15.0"
settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"
  CODE_SIGN_STYLE: Automatic
  DEVELOPMENT_TEAM: ""
targets:
  Buddy:
    type: application
    platform: iOS
    sources:
      - Sources
    resources:
      - path: dist
        type: folder
      - path: craft.config.json
        optional: true
    settings:
      INFOPLIST_FILE: Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.stacksjs.buddy
      SWIFT_VERSION: "5.0"
