/**
 * useColorMode / useDark — Theme management composables
 *
 * Detect system preference, persist user choice, toggle dark/light mode,
 * and sync across tabs — all with auto-cleanup.
 */

// =============================================================================
// Types
// =============================================================================

export type ColorMode = 'light' | 'dark' | 'auto'

/**
 * What may be *written* into storage for "follow the system".
 *
 * `'system'` is a common spelling for the same concept, and an app that already
 * persists it must not have that overwritten (stacksjs/stx#1788).
 */
export type AutoValue = 'auto' | 'system'

/** Accepted on input anywhere a ColorMode is; normalised to ColorMode. */
export type ColorModeInput = ColorMode | 'system'

export interface ColorModeOptions {
  /** localStorage key (default: 'stx-color-mode') */
  storageKey?: string
  /** Initial mode (default: 'auto'). `'system'` is accepted as an alias. */
  initialMode?: ColorModeInput
  /**
   * CSS class applied to `<html>` when dark (default: 'dark').
   *
   * Applied alongside `attribute` when both are set — they are not
   * alternatives in practice: the class drives the utility framework's `dark:`
   * variants, the attribute drives everything else. Pass `null` to opt out of
   * the class entirely.
   */
  darkClass?: string | null
  /** Data-attribute set to the resolved mode on `<html>`, e.g. 'data-theme'. */
  attribute?: string | null
  /**
   * Spelling written to storage for "follow the system" (default: whatever is
   * already stored, else `'auto'`).
   *
   * Both spellings are always *read*. This only controls what gets written, so
   * an app whose own pre-paint script expects `'system'` keeps working.
   */
  autoValue?: AutoValue
  /** Disable CSS transitions during mode switch to prevent flash (default: true) */
  disableTransitions?: boolean
}

/** Storage tokens meaning "follow the system". */
const AUTO_VALUES: readonly string[] = ['auto', 'system']

/**
 * Map any accepted spelling onto the canonical vocabulary, or null if the value
 * is not a color-mode preference at all.
 */
export function normalizeColorMode(value: unknown): ColorMode | null {
  if (value === 'light' || value === 'dark')
    return value
  if (typeof value === 'string' && AUTO_VALUES.includes(value))
    return 'auto'
  return null
}

export interface ColorModeRef {
  /** Current resolved mode ('light' or 'dark') */
  readonly mode: 'light' | 'dark'
  /** User preference ('light', 'dark', or 'auto') */
  readonly preference: ColorMode
  /** Convenience: true when resolved mode is dark */
  readonly isDark: boolean
  /** Set mode explicitly ('system' accepted as an alias for 'auto') */
  set: (mode: ColorModeInput) => void
  /** Toggle between light and dark (resets 'auto' to the opposite of current) */
  toggle: () => void
  /** Subscribe to mode changes */
  subscribe: (fn: (mode: 'light' | 'dark', preference: ColorMode) => void) => () => void
}

export interface DarkRef {
  /** Whether dark mode is active */
  readonly isDark: boolean
  /** Toggle dark mode */
  toggle: () => void
  /** Set dark mode explicitly */
  set: (dark: boolean) => void
  /** Subscribe to dark-mode changes */
  subscribe: (fn: (isDark: boolean) => void) => () => void
}

// =============================================================================
// useColorMode
// =============================================================================

/**
 * Full-featured color-mode manager.
 *
 * @example
 * ```ts
 * const { mode, isDark, toggle, set } = useColorMode()
 * toggle()           // switch light↔dark
 * set('auto')        // follow system preference
 * ```
 */
export function useColorMode(options: ColorModeOptions = {}): ColorModeRef {
  // The pre-paint boot script (stacksjs/stx#1794) publishes the app's
  // configured options on this global. Reading them makes a bare
  // useColorMode() agree with whatever already landed on <html> before first
  // paint — without this the composable would fall back to its own defaults,
  // read a different storage key, and undo the theme on hydration.
  // eslint-disable-next-line ts/no-explicit-any
  const boot = (typeof window !== 'undefined' ? (window as any).__STX_COLOR_MODE__ : null) as Partial<ColorModeOptions> | null

  /**
   * An explicit `null` means "do not manage this" — from the call site OR from
   * `app.colorMode`.
   *
   * `??` treats a boot-global `null` as unspecified, so it fell through to the
   * default: `attribute: null` looked fine because its fallback is null too,
   * while `darkClass: null` silently became `'dark'` (#1813). The boot payload
   * is generated by stx and always carries every key, so absent and
   * explicitly-null are distinguishable there — which is the whole point of the
   * global, since config is otherwise the one path that cannot say null.
   */
  function pick<T>(fromOptions: T | undefined, fromBoot: T | undefined, fallback: T): T {
    if (fromOptions !== undefined)
      return fromOptions
    if (boot && typeof boot === 'object' && fromBoot !== undefined)
      return fromBoot
    return fallback
  }

  const {
    storageKey = pick(undefined, boot?.storageKey, 'stx-color-mode'),
    initialMode = pick(undefined, boot?.initialMode, 'auto'),
    darkClass = pick(undefined, boot?.darkClass, 'dark' as string | null),
    attribute = pick(undefined, boot?.attribute, null as string | null),
    autoValue: autoValueOption = boot?.autoValue,
    disableTransitions = true,
  } = options

  let preference: ColorMode = normalizeColorMode(initialMode) ?? 'auto'
  let resolved: 'light' | 'dark' = 'light'
  const listeners: Set<(mode: 'light' | 'dark', preference: ColorMode) => void> = new Set()
  const cleanups: Array<() => void> = []

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  const isBrowser = typeof window !== 'undefined'

  function getSystemPreference(): 'light' | 'dark' {
    if (!isBrowser) return 'light'
    return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
  }

  function resolve(pref: ColorMode): 'light' | 'dark' {
    return pref === 'auto' ? getSystemPreference() : pref
  }

  function applyToDOM(mode: 'light' | 'dark') {
    if (!isBrowser) return
    const el = document.documentElement

    // Optionally suppress CSS transitions during switch
    if (disableTransitions) {
      el.style.setProperty('transition', 'none', 'important')
    }

    // Both, when both are configured (#1788). Passing `attribute` used to
    // silently disable `darkClass`, which made the composable unusable for any
    // app whose `dark:` utilities key off the class while its own CSS reads the
    // attribute — they are complements, not alternatives.
    if (attribute)
      el.setAttribute(attribute, mode)
    // Explicit add/remove rather than toggle(cls, force): very-happy-dom
    // ignores the force argument and plain-toggles, so every test asserting a
    // light mode would silently see the dark class ADDED.
    if (darkClass) {
      if (mode === 'dark')
        el.classList.add(darkClass)
      else
        el.classList.remove(darkClass)
    }

    if (disableTransitions) {
      // Force reflow then re-enable transitions
      // eslint-disable-next-line ts/no-unused-expressions
      el.offsetHeight
      el.style.removeProperty('transition')
    }
  }

  function readRaw(): string | null {
    if (!isBrowser) return null
    try { return localStorage.getItem(storageKey) }
    catch { /* private mode */ return null }
  }

  // The spelling written back for 'auto'. An explicit option wins; otherwise
  // whatever the app already had in storage, so its own pre-paint script keeps
  // reading a value it recognises.
  const storedRaw = readRaw()
  let autoValue: AutoValue = autoValueOption
    ?? (storedRaw !== null && AUTO_VALUES.includes(storedRaw) ? storedRaw as AutoValue : 'auto')

  function persist(pref: ColorMode) {
    if (!isBrowser) return
    try { localStorage.setItem(storageKey, pref === 'auto' ? autoValue : pref) }
    catch { /* quota / private mode */ }
  }

  // ---------------------------------------------------------------------------
  // Core update
  // ---------------------------------------------------------------------------

  /**
   * @param persistChoice - Only an explicit user choice is written back.
   *   Initialisation must not persist: it would stamp the resolved default over
   *   a stored value this composable didn't recognise, destroying it (#1788).
   */
  function update(pref: ColorModeInput, persistChoice = true) {
    preference = normalizeColorMode(pref) ?? 'auto'
    resolved = resolve(preference)
    applyToDOM(resolved)
    if (persistChoice)
      persist(preference)
    listeners.forEach(fn => fn(resolved, preference))
  }

  // ---------------------------------------------------------------------------
  // Initialise
  // ---------------------------------------------------------------------------

  update(normalizeColorMode(storedRaw) ?? initialMode, false)

  // ---------------------------------------------------------------------------
  // System preference change listener
  // ---------------------------------------------------------------------------

  if (isBrowser) {
    const mql = window.matchMedia('(prefers-color-scheme: dark)')
    const onSystemChange = () => {
      if (preference === 'auto') {
        resolved = getSystemPreference()
        applyToDOM(resolved)
        listeners.forEach(fn => fn(resolved, preference))
      }
    }
    mql.addEventListener('change', onSystemChange)
    cleanups.push(() => mql.removeEventListener('change', onSystemChange))

    // Cross-tab sync via storage event
    const onStorage = (e: StorageEvent) => {
      if (e.key !== storageKey) return
      const v = normalizeColorMode(e.newValue)
      if (v) {
        // Track the other tab's spelling too, so a write from here doesn't
        // convert the key out from under it.
        if (v === 'auto' && e.newValue && AUTO_VALUES.includes(e.newValue))
          autoValue = e.newValue as AutoValue
        preference = v
        resolved = resolve(v)
        applyToDOM(resolved)
        listeners.forEach(fn => fn(resolved, preference))
      }
    }
    window.addEventListener('storage', onStorage)
    cleanups.push(() => window.removeEventListener('storage', onStorage))
  }

  // Auto-cleanup
  if (typeof (globalThis as any).onDestroy === 'function') {
    ;(globalThis as any).onDestroy(() => {
      cleanups.forEach(fn => fn())
      listeners.clear()
    })
  }

  // ---------------------------------------------------------------------------
  // Public API
  // ---------------------------------------------------------------------------

  return {
    get mode() { return resolved },
    get preference() { return preference },
    get isDark() { return resolved === 'dark' },
    set(mode: ColorModeInput) { update(mode) },
    toggle() {
      update(resolved === 'dark' ? 'light' : 'dark')
    },
    subscribe(fn) {
      listeners.add(fn)
      return () => { listeners.delete(fn) }
    },
  }
}

// =============================================================================
// useDark
// =============================================================================

/**
 * Convenience wrapper — just isDark, toggle, set.
 *
 * @example
 * ```ts
 * const { isDark, toggle } = useDark()
 * toggle()
 * ```
 */
export function useDark(options: ColorModeOptions = {}): DarkRef {
  const cm = useColorMode(options)

  return {
    get isDark() { return cm.isDark },
    toggle() { cm.toggle() },
    set(dark: boolean) { cm.set(dark ? 'dark' : 'light') },
    subscribe(fn) {
      return cm.subscribe(mode => fn(mode === 'dark'))
    },
  }
}
