// @ts-nocheck - Skip type checking due to HeadersInit type constraints
import type { DevServerOptions } from './types'
import type { ProcessedShell } from '../app-shell'
import type { Route, RouteMatch } from '../router'
import { serve } from 'bun'
import fs from 'node:fs'
import path from 'node:path'
import { detectShell, processShell, composeShellWithPage, stripDocumentWrapper, isSpaNavigation } from '../app-shell'
import {
  getHmrServer,
  injectHotReload,
  isCssOnlyChange,
  shouldIgnoreFile,
  shouldReloadOnChange,
  stopHmrServer,
} from '../hot-reload'
import { partialsCache } from '../includes'
import { plugin as stxPlugin } from '../plugin'
import { createRouter, matchRoute, formatRoutes, findErrorPage } from '../router'
import {
  loadMiddlewareFromDirectory,
  runMiddleware,
  createMiddlewareContext,
  createRouteLocation,
  clearMiddleware,
  getMiddlewareNames,
} from '../route-middleware'
import { getPageMeta, resetHead } from '../head'
import { clearComponentCache } from '../utils'
import {
  buildCrosswindCSS,
  colors,
  extractSidebarConfig,
  findAvailablePort,
  injectCrosswindCSS,
  openNativeWindow,
  rebuildCrosswindCSS,
  setupKeyboardShortcuts,
} from './index'

// Interface for built page content
interface BuiltPage {
  route: Route
  content: string
}

// Helper to serve static files with proper content types
function serveStaticFile(filePath: string): Response {
  const file = Bun.file(filePath)
  const ext = path.extname(filePath).toLowerCase()

  const contentTypes: Record<string, string> = {
    '.html': 'text/html',
    '.css': 'text/css',
    '.js': 'text/javascript',
    '.json': 'application/json',
    '.png': 'image/png',
    '.jpg': 'image/jpeg',
    '.jpeg': 'image/jpeg',
    '.gif': 'image/gif',
    '.svg': 'image/svg+xml',
    '.ico': 'image/x-icon',
    '.woff': 'font/woff',
    '.woff2': 'font/woff2',
    '.ttf': 'font/ttf',
    '.otf': 'font/otf',
    '.eot': 'application/vnd.ms-fontobject',
  }

  // In development, disable caching for JS/CSS files so changes reflect immediately
  const noCacheExtensions = ['.js', '.css', '.json']
  const cacheHeaders = noCacheExtensions.includes(ext)
    ? {
        'Cache-Control': 'no-store, no-cache, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0',
      }
    : {}

  return new Response(file, {
    headers: {
      'Content-Type': contentTypes[ext] || 'application/octet-stream',
      ...cacheHeaders,
    },
  })
}

/**
 * Serve a full STX application with file-based routing
 *
 * Directory structure:
 *   pages/
 *     index.stx       → /
 *     about.stx       → /about
 *     chat/
 *       index.stx     → /chat
 *       [id].stx      → /chat/:id (dynamic route)
 *   components/       → Shared components
 *   public/           → Static assets
 */
export async function serveApp(appDir: string = '.', options: DevServerOptions = {}): Promise<boolean> {
  const port = options.port || 3000
  const watch = options.watch !== false
  const hotReload = options.hotReload !== false && watch

  let hmrServer: ReturnType<typeof getHmrServer> | null = null
  let actualHmrPort = options.hmrPort || port + 1

  // Resolve app directory, respecting the stx root config
  const absoluteAppDir = path.resolve(appDir)
  const { loadStxConfig } = await import('../')
  const projectConfig = await loadStxConfig()
  const stxRoot = projectConfig.root && projectConfig.root !== '.'
    ? path.join(absoluteAppDir, projectConfig.root)
    : absoluteAppDir
  const pagesDirName = projectConfig.pagesDir || 'pages'
  const pagesDir = path.join(stxRoot, pagesDirName)

  // Check if pages directory exists
  if (!fs.existsSync(pagesDir)) {
    console.error(`${colors.red}Error: No '${pagesDirName}' directory found in ${colors.bright}${stxRoot}${colors.reset}`)
    console.log(`${colors.dim}Create a ${pagesDirName}/ directory with .stx files to define your routes.${colors.reset}`)
    console.log(`${colors.dim}Example: ${pagesDirName}/index.stx for the homepage.${colors.reset}`)
    return false
  }

  // Create router from stx root (where pages/ lives)
  const routes = createRouter(stxRoot)

  if (routes.length === 0) {
    console.error(`${colors.red}Error: No page files found in ${colors.bright}${pagesDir}${colors.reset}`)
    return false
  }

  console.log(`${colors.blue}Found ${colors.bright}${routes.length}${colors.blue} routes${colors.reset}`)

  // Detect app shell (app.stx) — DEPRECATED in favor of layouts + autoShell.
  // The document shell is now auto-generated by the framework.
  // Shell detection is kept for backwards compat but new apps should use layouts/default.stx.
  let shell: ProcessedShell | null = null
  if (options.stxOptions?.shell !== false) {
    const shellPath = detectShell(absoluteAppDir, options.stxOptions?.shell)
    if (shellPath) {
      shell = await processShell(shellPath, options.stxOptions || {})
      if (shell) {
        console.log(`${colors.blue}Using app shell: ${colors.bright}${path.relative(absoluteAppDir, shellPath)}${colors.reset} ${colors.dim}(deprecated: use layouts/default.stx instead)${colors.reset}`)
      }
    }
  }

  // Load route middleware from middleware/ directory
  clearMiddleware() // Clear any previously registered middleware
  await loadMiddlewareFromDirectory(absoluteAppDir)
  const loadedMiddleware = getMiddlewareNames()
  if (loadedMiddleware.length > 0) {
    console.log(`${colors.blue}Loaded ${colors.bright}${loadedMiddleware.length}${colors.blue} middleware: ${colors.dim}${loadedMiddleware.join(', ')}${colors.reset}`)
  }

  // Load API routes and custom router from stx.config.ts
  let apiRoutes: Record<string, (request: Request) => Response | Promise<Response>> = {}
  let customRouter: { handleRequest: (request: Request) => Response | Promise<Response> } | null = null
  try {
    const { loadStxConfig } = await import('../')
    const projectConfig = await loadStxConfig()
    if (projectConfig?.apiRouter) {
      customRouter = projectConfig?.apiRouter
      console.log(`${colors.blue}Using custom router for API handling${colors.reset}`)
    }
    if (projectConfig?.apiRoutes) {
      apiRoutes = projectConfig.apiRoutes
      const routeCount = Object.keys(apiRoutes).length
      if (routeCount > 0) {
        console.log(`${colors.blue}Loaded ${colors.bright}${routeCount} API route${routeCount > 1 ? 's' : ''}${colors.reset}`)
      }
    }

    // Start broadcasting server if enabled, then auto-discover channels.ts
    if (projectConfig?.broadcasting?.enabled) {
      try {
        const { startBroadcasting, loadChannels } = await import('../broadcasting')
        const bcConfig = projectConfig.broadcasting
        await startBroadcasting(bcConfig)
        const bcPort = bcConfig.port ?? 6001
        console.log(`${colors.magenta}Broadcasting on ${colors.cyan}ws://localhost:${bcPort}/ws${colors.reset}`)

        // Auto-discover channels.ts at project root
        const channelsFile = path.join(process.cwd(), 'channels.ts')
        if (fs.existsSync(channelsFile)) {
          try {
            const count = await loadChannels(channelsFile)
            console.log(`${colors.blue}Loaded ${colors.bright}${count} broadcast channel${count !== 1 ? 's' : ''}${colors.blue} from channels.ts${colors.reset}`)
          }
          catch (err: any) {
            console.warn(`${colors.yellow}Failed to load channels.ts: ${err.message}${colors.reset}`)
          }
        }
      }
      catch (err: any) {
        console.warn(`${colors.yellow}Broadcasting failed to start: ${err.message}${colors.reset}`)
      }
    }
  }
  catch { /* no config or no apiRoutes */ }

  // Create output directory
  const outputDir = path.join(absoluteAppDir, '.stx/output')
  fs.mkdirSync(outputDir, { recursive: true })

  // Built pages cache
  const builtPages: Map<string, BuiltPage> = new Map()

  // Render a custom error page if it exists in the pages directory
  const renderErrorPage = async (statusCode: number): Promise<string | null> => {
    const errorPagePath = findErrorPage(pagesDir, statusCode)
    if (!errorPagePath) return null

    try {
      const result = await Bun.build({
        entrypoints: [errorPagePath],
        outdir: outputDir,
        plugins: [stxPlugin],
        publicPath: '/',
        define: {
          'process.env.NODE_ENV': '"development"',
        },
        ...options.stxOptions,
      })

      if (!result.success) return null

      const htmlOutput = result.outputs.find(o => o.path.endsWith('.html'))
      if (!htmlOutput) return null

      return await Bun.file(htmlOutput.path).text()
    }
    catch {
      return null
    }
  }

  // Build a single page file by processing the template directly
  // This matches the approach used by bun-plugin-stx/serve (which powers buddy dev)
  // instead of using Bun.build() which has issues with HTML asset resolution
  const buildPage = async (route: Route): Promise<BuiltPage | null> => {
    try {
      const { processDirectives, extractVariables, defaultConfig, loadStxConfig, injectRouterScript } = await import('../')

      // Load project stx.config.ts (e.g. partialsDir, componentsDir, layoutsDir)
      const projectConfig = await loadStxConfig()

      const content = await Bun.file(route.filePath).text()

      // Extract and classify script tags using unified classifier
      const { classifyAllScripts } = await import('../')
      const classified = classifyAllScripts(content)
      const clientScripts = classified.client.map(s => s.fullTag)
      const serverScripts = classified.server.map(s => s.content)
      // Signals scripts stay in template — handled by processDirectives/processSignals

      // Remove server and client script tags from template, keep signals scripts
      let templateContent = content
      for (const s of classified.server) {
        templateContent = templateContent.replace(s.fullTag, '')
      }
      for (const s of classified.client) {
        templateContent = templateContent.replace(s.fullTag, '')
      }

      // Create context and extract variables
      const context: Record<string, any> = {
        __filename: route.filePath,
        __dirname: path.dirname(route.filePath),
      }

      for (const scriptBody of serverScripts) {
        await extractVariables(scriptBody, context, route.filePath)
      }

      // Process template directives
      const dependencies = new Set<string>()
      let output = await processDirectives(templateContent, context, route.filePath, {
        ...defaultConfig,
        ...projectConfig,
        ...options.stxOptions,
        autoShell: true,
      }, dependencies)

      // Inject SPA router (skip when using shell — router goes in shell composition)
      if (!shell) {
        output = injectRouterScript(output)
      }

      // Re-inject client scripts before </body>
      if (clientScripts.length > 0) {
        const scriptsHtml = clientScripts.join('\n')
        const bodyIdx = output.lastIndexOf('</body>')
        if (bodyIdx !== -1) {
          output = output.slice(0, bodyIdx) + scriptsHtml + '\n</body>' + output.slice(bodyIdx + 7)
        }
        else {
          output += `\n${scriptsHtml}`
        }
      }

      // Shell mode: strip document wrapper from page output so it doesn't nest
      // inside the shell's own <!DOCTYPE>/html/head/body structure.
      // Preserves page scripts and styles as fragment content.
      if (shell) {
        output = stripDocumentWrapper(output)
      }

      return { route, content: output }
    }
    catch (error) {
      console.error(`${colors.red}Error building ${colors.bright}${route.pattern}${colors.reset}:`, error)
      return null
    }
  }

  // Build all pages
  const buildAllPages = async (): Promise<boolean> => {
    builtPages.clear()

    for (const route of routes) {
      const built = await buildPage(route)
      if (built) {
        builtPages.set(route.pattern, built)
      }
    }

    return builtPages.size > 0
  }

  // Initial build
  console.log(`${colors.blue}Building pages...${colors.reset}`)
  const buildSuccess = await buildAllPages()
  if (!buildSuccess) {
    console.error(`${colors.red}No pages were successfully built${colors.reset}`)
    return false
  }

  // Build Crosswind CSS if config exists
  await buildCrosswindCSS(absoluteAppDir)

  // Find available port
  let actualPort = port
  try {
    actualPort = await findAvailablePort(port)
    if (actualPort !== port) {
      console.log(`${colors.yellow}Port ${port} is busy, using port ${actualPort} instead${colors.reset}`)
    }
  }
catch {
    console.error(`${colors.red}Could not find an available port${colors.reset}`)
    return false
  }

  // Start HMR server
  if (hotReload) {
    const desiredHmrPort = options.hmrPort || actualPort + 1
    hmrServer = getHmrServer({ wsPort: desiredHmrPort, verbose: false })
    actualHmrPort = hmrServer.start(desiredHmrPort)
  }

  // Inject route params into HTML content via stx runtime
  const injectRouteParams = (content: string, params: Record<string, string>): string => {
    // Use stx.setRouteParams() which internally handles window access
    const paramsScript = `<script>(function(){var s=typeof stx!=='undefined'?stx:{};s._rp=${JSON.stringify(params)};if(s.setRouteParams)s.setRouteParams(s._rp);})()</script>`
    // Insert before closing </head> or at start of <body>
    if (content.includes('</head>')) {
      return content.replace('</head>', `${paramsScript}</head>`)
    }
    if (content.includes('<body')) {
      return content.replace(/<body([^>]*)>/, `<body$1>${paramsScript}`)
    }
    return paramsScript + content
  }

  // Start server
  console.log(`${colors.blue}Starting server...${colors.reset}`)
  const server = serve({
    port: actualPort,
    async fetch(request) {
      const url = new URL(request.url)

      // Serve static files from public/
      const publicPath = path.join(absoluteAppDir, 'public', url.pathname)
      if (fs.existsSync(publicPath) && fs.statSync(publicPath).isFile()) {
        return serveStaticFile(publicPath)
      }

      // Serve static files from dist/ (for Crosswind CSS etc.)
      const distPath = path.join(absoluteAppDir, url.pathname)
      if (fs.existsSync(distPath) && fs.statSync(distPath).isFile()) {
        return serveStaticFile(distPath)
      }

      // Serve files from output directory
      const outputPath = path.join(outputDir, url.pathname)
      if (fs.existsSync(outputPath) && fs.statSync(outputPath).isFile()) {
        return serveStaticFile(outputPath)
      }

      // Handle requests via custom router (e.g. @stacksjs/bun-router)
      // Supports both API routes (routes/api.ts) and web routes (routes/web.ts)
      if (customRouter) {
        try {
          const routerResponse = await customRouter.handleRequest(request)
          // Only use the router response if it's not a 404 (let STX pages handle those)
          if (routerResponse.status !== 404) {
            return routerResponse
          }
        }
        catch { /* router error — fall through to STX pages */ }
      }

      // Handle API routes from stx.config.ts (fallback)
      if (apiRoutes[url.pathname]) {
        try {
          return await apiRoutes[url.pathname](request)
        }
        catch (err: any) {
          return new Response(JSON.stringify({ error: err.message }), {
            status: 500,
            headers: { 'Content-Type': 'application/json' },
          })
        }
      }

      // Match route
      const routeMatch = matchRoute(url.pathname, routes)

      if (routeMatch) {
        const builtPage = builtPages.get(routeMatch.route.pattern)
        if (builtPage) {
          // Get page metadata (middleware, etc.)
          const pageMeta = getPageMeta()

          // Run route param validation if defined
          if (pageMeta.validate) {
            const isValid = await pageMeta.validate({ params: routeMatch.params })
            if (!isValid) {
              // Validation failed — render 404
              const custom404 = await renderErrorPage(404)
              if (custom404) {
                let content = custom404
                content = await injectCrosswindCSS(content)
                if (hotReload) {
                  content = injectHotReload(content, actualHmrPort)
                }
                return new Response(content, {
                  status: 404,
                  headers: { 'Content-Type': 'text/html' },
                })
              }
              return new Response('Not Found', { status: 404 })
            }
          }

          // Run route middleware if defined
          if (pageMeta.middleware) {
            const toRoute = createRouteLocation(
              url.pathname,
              routeMatch.params,
              pageMeta,
              url.search
            )

            const middlewareContext = createMiddlewareContext(toRoute, null, request)
            const middlewareResult = await runMiddleware(pageMeta.middleware, middlewareContext)

            // Handle redirect
            if (middlewareResult.redirect) {
              const redirectUrl = middlewareResult.redirect.path
              const statusCode = middlewareResult.redirect.options.redirectCode || 302

              // Apply any response headers from middleware
              const headers = new Headers(middlewareResult.responseHeaders)
              headers.set('Location', redirectUrl)

              return new Response(null, {
                status: statusCode,
                headers,
              })
            }

            // Handle abort
            if (middlewareResult.abort) {
              const { statusCode, message } = middlewareResult.abort.error
              return new Response(
                `<!DOCTYPE html><html><head><title>Error ${statusCode}</title></head><body><h1>Error ${statusCode}</h1><p>${message}</p></body></html>`,
                {
                  status: statusCode,
                  headers: { 'Content-Type': 'text/html' },
                }
              )
            }

            // Inject middleware state into page via stx runtime
            if (Object.keys(middlewareResult.state).length > 0) {
              const stateScript = `<script>(function(){var s=typeof stx!=='undefined'?stx:{};s._ms=${JSON.stringify(middlewareResult.state)};if(s.setMiddlewareState)s.setMiddlewareState(s._ms);})()</script>`
              builtPage.content = builtPage.content.replace('</head>', `${stateScript}</head>`)
            }
          }

          let content = builtPage.content

          // Shell mode: SPA navigation returns page fragment only
          if (shell && isSpaNavigation(request)) {
            // Inject route params into fragment
            if (Object.keys(routeMatch.params).length > 0) {
              content = injectRouteParams(content, routeMatch.params)
            }
            // Generate Crosswind CSS for this page's utility classes and include in fragment
            // Without this, SPA-navigated pages have no CSS for their utility classes
            content = await injectCrosswindCSS(content)
            return new Response(content, {
              headers: {
                'Content-Type': 'text/html',
                'X-STX-Fragment': 'true',
                'Cache-Control': 'no-store, no-cache, must-revalidate',
              },
            })
          }

          // Shell mode: direct request wraps page in shell
          if (shell) {
            content = composeShellWithPage(shell, content)
          }

          // Inject route params for dynamic routes
          if (Object.keys(routeMatch.params).length > 0) {
            content = injectRouteParams(content, routeMatch.params)
          }

          // Inject Crosswind CSS
          content = await injectCrosswindCSS(content)

          // Inject HMR client
          if (hotReload) {
            content = injectHotReload(content, actualHmrPort)
          }

          // Inject native sidebar styles and flag when running in native mode
          if (options.native) {
            const nativeSidebarInjection = `<style>[data-stx-sidebar],.stx-sidebar{display:none!important}</style><script>window.__craftNativeSidebar=true;document.documentElement.classList.add('has-native-sidebar')</script>`
            if (content.includes('<head>')) {
              content = content.replace('<head>', `<head>${nativeSidebarInjection}`)
            }
            else {
              content = `<head>${nativeSidebarInjection}</head>` + content
            }
          }

          return new Response(content, {
            headers: {
              'Content-Type': 'text/html',
              'Cache-Control': 'no-store, no-cache, must-revalidate',
              'Pragma': 'no-cache',
              'Expires': '0',
            },
          })
        }
      }

      // SPA fallback: serve index page for unmatched routes
      const indexPage = builtPages.get('/')
      if (indexPage) {
        let content = indexPage.content
        content = await injectCrosswindCSS(content)
        if (hotReload) {
          content = injectHotReload(content, actualHmrPort)
        }
        // Inject native sidebar styles and flag when running in native mode
        if (options.native) {
          const nativeSidebarInjection = `<style>[data-stx-sidebar],.stx-sidebar{display:none!important}</style><script>window.__craftNativeSidebar=true;document.documentElement.classList.add('has-native-sidebar')</script>`
          if (content.includes('<head>')) {
            content = content.replace('<head>', `<head>${nativeSidebarInjection}`)
          }
          else {
            content = `<head>${nativeSidebarInjection}</head>` + content
          }
        }
        return new Response(content, {
          headers: {
            'Content-Type': 'text/html',
            'Cache-Control': 'no-store, no-cache, must-revalidate',
            'Pragma': 'no-cache',
            'Expires': '0',
          },
        })
      }

      // Try custom 404 error page
      const custom404 = await renderErrorPage(404)
      if (custom404) {
        let content = custom404
        content = await injectCrosswindCSS(content)
        if (hotReload) {
          content = injectHotReload(content, actualHmrPort)
        }
        return new Response(content, {
          status: 404,
          headers: { 'Content-Type': 'text/html' },
        })
      }

      return new Response('Not Found', { status: 404 })
    },
    async error(error) {
      // Try custom 500 error page
      const custom500 = await renderErrorPage(500)
      if (custom500) {
        return new Response(custom500, {
          status: 500,
          headers: { 'Content-Type': 'text/html' },
        })
      }

      return new Response(`<pre>${error}\n${error.stack}</pre>`, {
        headers: { 'Content-Type': 'text/html' },
      })
    },
  })

  // Print output
  console.clear()
  console.log(`\n${colors.blue}stx${colors.reset}  ${colors.green}${process.env.stx_VERSION || 'v0.0.10'}${colors.reset}  ${colors.dim}ready in ${Math.random() * 10 + 5 | 0}.${Math.random() * 90 + 10 | 0} ms${colors.reset}`)
  console.log(`\n${colors.bright}→  ${colors.cyan}http://localhost:${actualPort}/${colors.reset}`)
  if (hotReload) {
    console.log(`${colors.dim}   HMR: ws://localhost:${actualHmrPort}${colors.reset}`)
  }

  // Print routes
  console.log(`\n${colors.yellow}Routes:${colors.reset}`)
  const routeStrings = formatRoutes(routes, absoluteAppDir)
  routeStrings.forEach((str, i) => {
    const isLast = i === routeStrings.length - 1
    const prefix = isLast ? '└─ ' : '├─ '
    console.log(`  ${colors.green}${prefix}${colors.reset}${str}`)
  })

  console.log(`\nPress ${colors.cyan}h${colors.reset} + ${colors.cyan}Enter${colors.reset} to show shortcuts`)

  // Set up keyboard shortcuts
  setupKeyboardShortcuts(server.url.toString(), () => {
    if (hmrServer) stopHmrServer()
    server.stop()
  })

  // Open native window if requested
  if (options.native) {
    // For app mode, try to find sidebar config from index page or layout
    let sidebarConfig
    const indexPath = path.join(pagesDir, 'index.stx')
    if (fs.existsSync(indexPath)) {
      const templateContent = await Bun.file(indexPath).text()
      sidebarConfig = extractSidebarConfig(templateContent)
    }

    await openNativeWindow(actualPort, {
      title: path.basename(absoluteAppDir) || 'stx App',
      nativeSidebar: !!sidebarConfig,
      sidebarConfig,
    })
  }

  // File watching
  if (watch) {
    console.log(`${colors.blue}Watching for changes...${colors.reset}`)

    // Check if file is a static asset (in public/ directory)
    const isStaticAsset = (filename: string): boolean => {
      return filename.startsWith('public/') || filename.startsWith('public\\')
    }

    // Check if file is a template/source file that needs rebuild
    const isTemplateFile = (filename: string): boolean => {
      const ext = filename.toLowerCase()
      return ext.endsWith('.stx') || ext.endsWith('.html') || ext.endsWith('.md')
    }

    // eslint-disable-next-line pickier/no-unused-vars
    const watcher = fs.watch(absoluteAppDir, { recursive: true }, async (eventType, filename) => {
      if (!filename || shouldIgnoreFile(filename)) return

      if (shouldReloadOnChange(filename)) {
        // For static assets (public/), just trigger reload without rebuilding
        if (isStaticAsset(filename)) {
          console.log(`${colors.cyan}${filename} changed${colors.reset}`)
          if (hotReload && hmrServer) {
            hmrServer.reload(filename)
          }
        }
        // For template files, rebuild pages
        else if (isTemplateFile(filename)) {
          console.log(`${colors.yellow}${filename} changed, rebuilding...${colors.reset}`)
          // Clear all caches to ensure fresh content
          partialsCache.clear()
          clearComponentCache()
          // Rebuild shell if shell file changed
          if (shellPath && filename) {
            const changedPath = path.resolve(absoluteAppDir, filename)
            if (changedPath === shellPath || path.basename(shellPath) === filename) {
              const newShell = await processShell(shellPath, options.stxOptions || {})
              if (newShell) shell = newShell
            }
          }
          await buildAllPages()
          await rebuildCrosswindCSS(absoluteAppDir)

          if (hotReload && hmrServer) {
            hmrServer.reload(filename)
          }
        }
        // For other JS/TS files (could be components, lib, etc.), rebuild
        else {
          console.log(`${colors.yellow}${filename} changed, rebuilding...${colors.reset}`)
          // Clear all caches to ensure fresh content
          partialsCache.clear()
          clearComponentCache()
          await buildAllPages()

          if (hotReload && hmrServer) {
            hmrServer.reload(filename)
          }
        }
      }
else if (isCssOnlyChange(filename)) {
        console.log(`${colors.cyan}CSS ${filename} changed${colors.reset}`)
        if (hotReload && hmrServer) {
          hmrServer.updateCss(filename)
        }
      }
    })

    process.on('SIGINT', () => {
      watcher.close()
      if (hmrServer) stopHmrServer()
      server.stop()
      process.exit(0)
    })
  }

  return true
}
