/**
 * A Crosswind config edit invalidates the SSG cache (stacksjs/stx#1940).
 *
 * The page cache keyed on each page's `.stx` file and the dependencies collected
 * while rendering it. The Crosswind config is in neither, yet it decides the
 * stylesheet every page ships — so editing a preflight or the safelist produced
 * a build that reported every route `Cached`, exited 0, and emitted the old CSS.
 *
 * That is worse than an ordinary stale cache. The config is where preflights
 * live, so the one edit that applies to every page was the one the key ignored,
 * and the build gives no signal at all: green, 24/24, wrong stylesheet. Anyone
 * hitting it concludes their CSS is wrong and debugs the wrong file.
 *
 * Asserted through `cachedCount`, which is the number the build prints. The
 * emitted CSS is generated by machinery with its own module-level caches, so a
 * test that only checked the stylesheet could pass or fail for reasons that have
 * nothing to do with the cache key. What is under test is whether the second
 * build re-rendered.
 *
 * The salt is exercised through the `cacheSalt` option rather than by editing a
 * real `crosswind.config.ts`, because the config resolves from `process.cwd()`
 * and mutating that mid-suite is a global. `cacheSalt` is the same value on the
 * same code path — the default simply computes the Crosswind digest into it.
 */

import { afterAll, beforeEach, describe, expect, it } from 'bun:test'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { fingerprintConfig } from '../../src/dev-server/crosswind'
import { generateStaticSite } from '../../src/ssg'

const TMP = fs.mkdtempSync(path.join(os.tmpdir(), 'stx-cw-cache-'))
const pagesDir = path.join(TMP, 'pages')
const outputDir = path.join(TMP, 'dist')
const cacheDir = path.join(TMP, 'cache')

afterAll(() => fs.rmSync(TMP, { recursive: true, force: true }))

beforeEach(async () => {
  fs.rmSync(pagesDir, { recursive: true, force: true })
  fs.rmSync(cacheDir, { recursive: true, force: true })
  await fs.promises.mkdir(pagesDir, { recursive: true })
  await Bun.write(
    path.join(pagesDir, 'index.stx'),
    '<html><head><title>Home</title></head><body><h1 class="text-red-500">Home</h1></body></html>',
  )
})

function build(cacheSalt?: string) {
  return generateStaticSite({
    pagesDir,
    outputDir,
    cacheDir,
    sitemap: false,
    robots: false,
    cache: true,
    cleanOutput: false,
    ...(cacheSalt === undefined ? {} : { cacheSalt }),
  })
}

describe('the build cache', () => {
  it('reports a hit on an unchanged rebuild', async () => {
    // The control. Without it, a fix that simply disabled caching would satisfy
    // every other assertion in this file.
    const first = await build()
    expect(first.cachedCount).toBe(0)
    expect(first.successCount).toBe(1)

    const second = await build()
    expect(second.cachedCount).toBe(1)
  })

  it('misses every page when the salt changes', async () => {
    // The behaviour the issue is about: nothing in `pages/` moved, and the
    // rebuild must still re-render.
    await build('config-v1')
    expect((await build('config-v1')).cachedCount).toBe(1)

    const afterEdit = await build('config-v2')
    expect(afterEdit.cachedCount).toBe(0)
    expect(afterEdit.successCount).toBe(1)
  })

  it('goes back to hitting once the salt settles', async () => {
    // A salt that changed every build would "fix" the issue by never caching.
    await build('config-v2')

    expect((await build('config-v2')).cachedCount).toBe(1)
  })
})

describe('the config fingerprint', () => {
  it('changes when a preflight rule is added', () => {
    // The reported edit: a rule appended to a registered preflight string.
    const before = fingerprintConfig({ preflights: ['.a { color: red; }'] })
    const after = fingerprintConfig({ preflights: ['.a { color: red; }\n.stx-cache-repro { color: red; }'] })

    expect(after).not.toBe(before)
  })

  it('changes when the safelist gains an entry', () => {
    const before = fingerprintConfig({ safelist: ['bg-red-500'] })
    const after = fingerprintConfig({ safelist: ['bg-red-500', 'bg-blue-500'] })

    expect(after).not.toBe(before)
  })

  it('changes when a theme token moves', () => {
    const before = fingerprintConfig({ theme: { colors: { gray: { 600: '#52525b' } } } })
    const after = fingerprintConfig({ theme: { colors: { gray: { 600: '#3f3f46' } } } })

    expect(after).not.toBe(before)
  })

  it('changes when a function-valued entry is edited', () => {
    // `JSON.stringify` drops functions, so a digest built on it alone reports
    // these two configs as identical — silently the same staleness one level up.
    const before = fingerprintConfig({ plugins: [() => 'a'] })
    const after = fingerprintConfig({ plugins: [() => 'b'] })

    expect(after).not.toBe(before)
  })

  it('is stable for equal configs, or every build is a miss', () => {
    const config = { theme: { colors: { gray: { 600: '#52525b' } } }, safelist: ['a'] }

    expect(fingerprintConfig(config)).toBe(fingerprintConfig({ ...config }))
  })

  it('survives a cycle instead of collapsing to a constant', () => {
    // Throwing here degrades to 'unhashable' — a cache key that never changes,
    // which is the original bug restored.
    const cyclic: Record<string, unknown> = { safelist: ['a'] }
    cyclic.self = cyclic
    const other: Record<string, unknown> = { safelist: ['b'] }
    other.self = other

    const a = fingerprintConfig(cyclic)
    expect(a).not.toBe('unhashable')
    expect(fingerprintConfig(other)).not.toBe(a)
  })
})
