import type { Route } from './types'
import fs from 'node:fs'
import path from 'node:path'
import { isNonPageRoutePattern } from './page-routes'

/**
 * Write the route declaration consumed by `CheckHref` in `@stacksjs/stx`.
 *
 * This used to emit `declare module "stx/routes"`, a specifier nothing in the
 * source tree declares or imports. TypeScript therefore read it as an ambient
 * module declaration rather than an augmentation, so it constrained nothing and
 * `navigate('/typo')` type-checked (stacksjs/stx#1887).
 *
 * Two details are load-bearing rather than cosmetic:
 *
 *  - the trailing `export {}` makes this a module, so `declare module` is an
 *    augmentation of the real package instead of a replacement for it;
 *  - non-page routes are filtered out, which `generateRouteManifest` already
 *    did and this did not — the two artifacts disagreed about membership.
 */
export function generateRouteTypes(routes: Route[], outputDir: string): void {
  const pageRoutes = routes.filter(r => !isNonPageRoutePattern(r.pattern))

  const lines = ['// Auto-generated by STX - do not edit']

  if (pageRoutes.length === 0) {
    // No interface at all. An empty one leaves `keyof KnownRoutes` as `never`,
    // which widens back to `string` — emitting it would look like a constraint
    // while being none.
    lines.push('// No page routes found — route paths stay typed as string.', 'export {}', '')
  }
  else {
    lines.push(`declare module '@stacksjs/stx' {`, '  interface KnownRoutes {')

    for (const route of pageRoutes) {
      const paramEntries: string[] = []
      for (const p of route.params) {
        // A catch-all captures one string containing slashes, not an array —
        // `/blog/:slug*` against `/blog/2024/jan/hi` yields
        // `{ slug: '2024/jan/hi' }`.
        //
        // An optional segment is optional in the params too, or $path() would
        // demand an argument for `/settings/:tab?` — a route whose whole point
        // is that the segment can be absent.
        const optional = route.pattern.includes(`:${p}?`) ? '?' : ''
        paramEntries.push(`${p}${optional}: string`)
      }
      const paramsStr = paramEntries.join('; ')
      lines.push(`    '${route.pattern}': { ${paramsStr} }`)
    }

    lines.push('  }', '}', '', 'export {}', '')
  }

  const contents = lines.join('\n')
  const target = path.join(outputDir, 'route-types.d.ts')

  try {
    // Idempotent: an unchanged rewrite would look like an edit to a watcher.
    if (fs.existsSync(target) && fs.readFileSync(target, 'utf8') === contents)
      return
    fs.mkdirSync(outputDir, { recursive: true })
    fs.writeFileSync(target, contents)
  }
  catch {
    // Read-only FS, race — the declaration is a developer convenience.
  }
}

/**
 * Generate a route manifest file (.stx/routes.ts).
 *
 * Produces a TypeScript module exporting the full route array with patterns,
 * file paths, params, and layout references. Similar to Nuxt's .nuxt/routes.mjs.
 */
export function generateRouteManifest(routes: Route[], outputDir: string, pagesDir: string): void {
  const cwd = process.cwd()
  const relativePages = path.relative(cwd, pagesDir)

  // Filter out non-page files (components, layouts, partials). The scanner
  // already skips these, so this is belt-and-braces for routes added by hand
  // via `addRoute` — but it shares the scanner's rule now rather than
  // restating a shallower one (#1866).
  const pageRoutes = routes.filter(r => !isNonPageRoutePattern(r.pattern))

  const lines = [
    '// Auto-generated by stx — do not edit',
    `// Source: ${relativePages || 'pages'}/`,
    '',
    'export const routes = [',
  ]

  for (const route of pageRoutes) {
    const relFile = path.relative(cwd, route.filePath).replace(/\\/g, '/')
    const params = JSON.stringify(route.params)
    const layoutStr = route.layout
      ? `, layout: '${path.relative(cwd, route.layout).replace(/\\/g, '/')}'`
      : ''
    lines.push(`  { pattern: '${route.pattern}', filePath: '${relFile}', isDynamic: ${route.isDynamic}, params: ${params}${layoutStr} },`)
  }

  lines.push('] as const', '')
  lines.push('export type RouteName = typeof routes[number][\'pattern\']', '')

  fs.mkdirSync(outputDir, { recursive: true })
  fs.writeFileSync(path.join(outputDir, 'routes.ts'), lines.join('\n'))
}
