import fs from 'node:fs'
import path from 'node:path'
import type { Route } from './types'

export function generateRouteTypes(routes: Route[], outputDir: string): void {
  const lines = [
    '// Auto-generated by STX - do not edit',
    'declare module "stx/routes" {',
    '  interface RouteMap {',
  ]

  for (const route of routes) {
    const paramEntries: string[] = []
    for (const p of route.params) {
      const type = route.pattern.includes(`:${p}*`) ? 'string[]' : 'string'
      paramEntries.push(`${p}: ${type}`)
    }
    const paramsStr = paramEntries.join('; ')
    lines.push(`    '${route.pattern}': { ${paramsStr} }`)
  }

  lines.push('  }', '}', '')

  fs.mkdirSync(outputDir, { recursive: true })
  fs.writeFileSync(path.join(outputDir, 'route-types.d.ts'), lines.join('\n'))
}
