/**
 * Generate a union of the layouts that exist on disk, so naming one wrong is a
 * type error rather than an unlayouted page (stacksjs/stx#1879 ask 3).
 *
 * `definePageMeta({ layout: 'app' })` now selects a layout, which makes the
 * name a load-bearing string — and a typo produces exactly the same render as a
 * correct name pointing at a missing file. Nuxt types `layout` as a union of
 * the files on disk for this reason; the failure is caught before the build,
 * not by reading the console afterwards.
 *
 * ## Why this augments the real package, not a synthetic specifier
 *
 * The route-type generator emits `declare module "stx/routes" { interface
 * RouteMap … }`, and nothing in the source tree declares or imports
 * `stx/routes` — so that map is a dangling declaration that cannot make
 * anything a type error. That is the same "typed and never read" shape #1879
 * is about, one level up, and repeating it here would produce a file that looks
 * like a fix and checks nothing.
 *
 * So the augmentation targets `@stacksjs/stx`, where `KnownLayouts` is really
 * declared and really referenced by `PageMeta['layout']`.
 *
 * @module layout-types
 */

import fs from 'node:fs'
import path from 'node:path'

/** The name of the generated declaration file, inside the state directory. */
export const LAYOUT_TYPES_FILE = 'layout-types.d.ts'

/**
 * Layout names in `layoutsDir`, without the `.stx` extension.
 *
 * Nested layouts keep their path (`admin/settings`), matching what the layout
 * resolver accepts. `_layout.stx` files are excluded: they are applied by
 * directory position, never named.
 */
export function discoverLayoutNames(layoutsDir: string): string[] {
  const names: string[] = []
  const walk = (dir: string, prefix: string): void => {
    let entries: fs.Dirent[]
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true })
    }
    catch {
      return
    }
    for (const entry of entries) {
      if (entry.name.startsWith('.'))
        continue
      const full = path.join(dir, entry.name)
      if (entry.isDirectory()) {
        walk(full, prefix ? `${prefix}/${entry.name}` : entry.name)
      }
      else if (entry.isFile() && entry.name.endsWith('.stx') && entry.name !== '_layout.stx') {
        const base = entry.name.slice(0, -'.stx'.length)
        names.push(prefix ? `${prefix}/${base}` : base)
      }
    }
  }
  walk(layoutsDir, '')
  return names.sort()
}

/** The declaration text for a set of layout names. */
export function renderLayoutTypes(names: readonly string[]): string {
  const lines = [
    '// Auto-generated by stx — do not edit.',
    '//',
    '// Makes `definePageMeta({ layout })` reject a name with no layout behind it.',
    '// Include this file in your tsconfig (it lives in the stx state directory,',
    '// `.stx/` by default) for the check to apply.',
    '',
  ]

  if (names.length === 0) {
    // An empty interface would leave `keyof KnownLayouts` as `never`, which the
    // fallback in head.ts widens back to `string`. Say so, rather than emitting
    // a file that looks like it constrains something.
    lines.push(
      '// No layouts found — `layout` stays typed as `string`.',
      'export {}',
      '',
    )
    return lines.join('\n')
  }

  lines.push(
    `declare module '@stacksjs/stx' {`,
    '  interface KnownLayouts {',
    ...names.map(name => `    '${name}': true`),
    '  }',
    '}',
    '',
    'export {}',
    '',
  )
  return lines.join('\n')
}

/**
 * Write the declaration for `layoutsDir` into `outputDir`.
 *
 * Best-effort and idempotent: an unwritable state directory is not a build
 * failure, and an unchanged file is left alone so watchers do not see a write
 * on every render.
 */
export function generateLayoutTypes(layoutsDir: string | undefined, outputDir: string): string[] {
  if (!layoutsDir)
    return []

  const abs = path.isAbsolute(layoutsDir) ? layoutsDir : path.resolve(process.cwd(), layoutsDir)
  const names = discoverLayoutNames(abs)
  const contents = renderLayoutTypes(names)
  const target = path.join(outputDir, LAYOUT_TYPES_FILE)

  try {
    if (fs.existsSync(target) && fs.readFileSync(target, 'utf8') === contents)
      return names
    fs.mkdirSync(outputDir, { recursive: true })
    fs.writeFileSync(target, contents)
  }
  catch {
    // Read-only FS, race, etc. — the declaration is a developer convenience.
  }

  return names
}
