import fs from 'node:fs'
import path from 'node:path'
import { pathToFileURL } from 'node:url'
import { patternToRegex } from 'stx-router'
import { stateDir } from './state-dir'
import type { ApiHandlerContext } from './api-handler'
import type { ApiMethod } from './api-client'
import { resolveRuntimeConfig, withRuntimeConfig } from './runtime-config-server'

export interface ServerApiOptions {
  /** Relative to the project/config directory, not the template root. */
  dir?: string
}

export interface ServerApiRoute {
  pattern: string
  method: ApiMethod
  /** Source file in dev; bundled file relative to outputDir in the manifest. */
  filePath: string
}

const METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'] as const
// Discovery may be enabled by an embedded host/build option, without a config
// file. Keep those endpoint identities private even in a later registry build.
const discoveredSources = new Set<string>()

/** Only explicitly enabled callers scan server/api; discovery never executes user code. */
export function discoverServerApi(root: string, options: ServerApiOptions = {}): ServerApiRoute[] {
  const directory = path.resolve(root, options.dir ?? 'server/api')
  const routes: ServerApiRoute[] = []
  const signatures = new Map<string, string>()
  if (!fs.existsSync(directory)) return routes
  const files = Array.from(new Bun.Glob('**/*.{ts,js,mts,mjs}').scanSync({ cwd: directory })).sort()
  for (const file of files) {
    if (file.endsWith('.d.ts')) continue
    const withoutExtension = file.replace(/\.(?:ts|js|mts|mjs)$/, '')
    const parts = withoutExtension.split('/')
    let name = parts.pop()!
    const dot = name.lastIndexOf('.')
    const suffix = dot >= 0 ? name.slice(dot + 1) : 'get'
    const method = suffix.toUpperCase() as ApiMethod
    if (!METHODS.includes(method) || suffix !== suffix.toLowerCase())
      throw new Error(`Unsupported API method suffix in ${file}; use ${METHODS.map(value => value.toLowerCase()).join(', ')}`)
    if (dot >= 0) name = name.slice(0, dot)
    if (name !== 'index') parts.push(name)
    const names = new Set<string>()
    const segments = parts.map((part, index) => {
      const parameter = /^\[(\.\.\.)?([A-Za-z_]\w*)\]$/.exec(part)
      if (parameter) {
        if (names.has(parameter[2]) || (parameter[1] && index !== parts.length - 1))
          throw new Error(`Invalid API parameter in ${file}`)
        names.add(parameter[2])
        return `:${parameter[2]}${parameter[1] ? '*' : ''}`
      }
      if (!/^[\w-]+$/.test(part))
        throw new Error(`Unsupported API path segment ${part} in ${file}`)
      return part
    })
    const pattern = `/api${segments.length ? `/${segments.join('/')}` : ''}`
    const signature = `${method} ${pattern.replace(/:\w+/g, ':param')}`
    if (signatures.has(signature))
      throw new Error(`Ambiguous API route ${method} ${pattern}: ${signatures.get(signature)} and ${file}`)
    signatures.set(signature, file)
    const filePath = path.join(directory, file)
    discoveredSources.add(path.resolve(filePath))
    discoveredSources.add(fs.realpathSync(filePath))
    routes.push({ pattern, method, filePath })
  }
  // Compare left to right, so literals win over params, and params over catch-all.
  return routes.sort((a, b) => {
    const left = a.pattern.split('/')
    const right = b.pattern.split('/')
    const rank = (part: string): number => part?.endsWith('*') ? 0 : part?.startsWith(':') ? 1 : 2
    for (let i = 0; i < Math.max(left.length, right.length); i++) {
      const delta = rank(right[i]) - rank(left[i])
      if (delta) return delta
    }
    return a.pattern.localeCompare(b.pattern) || a.method.localeCompare(b.method)
  })
}

/** The only generated imports are in a declaration file: no implementation enters a client graph. */
export async function generateApiTypes(root: string, routes: ServerApiRoute[]): Promise<string> {
  const target = stateDir(root, 'api-types.d.ts')
  const lines = ["// Generated by stx. Include this file in tsconfig.json.", "declare module '@stacksjs/stx/api-client' {", '  interface KnownApiRoutes {']
  for (const route of routes) {
    const specifier = `./${path.relative(path.dirname(target), route.filePath).replace(/\\/g, '/')}`
    const { params } = patternToRegex(route.pattern)
    lines.push(`    ${JSON.stringify(`${route.method} ${route.pattern}`)}: { params: { ${params.map(name => `${JSON.stringify(name)}: string`).join('; ')} }; response: Awaited<ReturnType<typeof import(${JSON.stringify(specifier)}).default>> }`)
  }
  lines.push('  }', '}', 'export {}', '')
  const content = lines.join('\n')
  if (!await Bun.file(target).exists() || await Bun.file(target).text() !== content)
    await Bun.write(target, content)
  return target
}

/** Bun bundles server code only, outside public/. Imported helpers are included. */
export async function buildServerApi(root: string, outputDir: string, options: ServerApiOptions = {}): Promise<ServerApiRoute[]> {
  const routes = discoverServerApi(root, options)
  await generateApiTypes(root, routes)
  const result: ServerApiRoute[] = []
  for (const route of routes) {
    const bundled = await Bun.build({ entrypoints: [route.filePath], target: 'bun', format: 'esm', minify: false, splitting: false })
    if (!bundled.success)
      throw new Error(`API build failed for ${route.filePath}: ${bundled.logs.join('\n')}`)
    const output = bundled.outputs.find(file => file.kind === 'entry-point')
    if (!output) throw new Error(`No API bundle for ${route.filePath}`)
    if (bundled.outputs.length !== 1)
      throw new Error(`API endpoint ${route.filePath} emits assets; package those explicitly instead`)
    const hash = new Bun.CryptoHasher('sha256').update(await output.arrayBuffer()).digest('hex').slice(0, 20)
    const filePath = `server/api/endpoint-${hash}.mjs`
    await Bun.write(path.join(outputDir, filePath), output)
    result.push({ ...route, filePath })
  }
  return result
}

type Handler = (request: Request, context: ApiHandlerContext) => unknown

/** Shared dispatcher used by development, production and embedded hosts. */
export function createApiDispatcher(routes: ServerApiRoute[], load: (route: ServerApiRoute) => Promise<Handler>): (request: Request) => Promise<Response | null> {
  const compiled = routes.map(route => ({ route, ...patternToRegex(route.pattern) }))
  return async (request) => {
    const pathname = new URL(request.url).pathname
    const matches = compiled.filter(entry => entry.regex.test(pathname))
    if (!matches.length) return null
    // Resolve the path first, THEN the method. POST /users/new must not fall
    // through to a lower-priority POST /users/:id when /users/new is GET-only.
    const pattern = matches[0].route.pattern
    const canonical = (value: string): string => value.replace(/:\w+/g, ':param')
    const candidates = matches.filter(entry => canonical(entry.route.pattern) === canonical(pattern))
    const method = request.method
    const matched = candidates.find(entry => entry.route.method === method) ?? (method === 'HEAD' ? candidates.find(entry => entry.route.method === 'GET') : undefined)
    if (!matched) {
      const allow = new Set(candidates.map(entry => entry.route.method as string))
      if (allow.has('GET')) allow.add('HEAD')
      allow.add('OPTIONS')
      return new Response(null, { status: method === 'OPTIONS' ? 204 : 405, headers: { Allow: Array.from(allow).sort().join(', ') } })
    }
    const match = matched.regex.exec(pathname)!
    const params: Record<string, string> = Object.create(null)
    try {
      matched.params.forEach((name, i) => { params[name] = decodeURIComponent(match[i + 1]) })
    }
    catch {
      return new Response('Invalid URL parameter encoding', { status: 400 })
    }
    try {
      const handler = await load(matched.route)
      if (typeof handler !== 'function')
        throw new Error(`API endpoint ${matched.route.filePath} must default-export a handler`)
      const value = await handler(request, { params })
      const response = value instanceof Response ? value : value === undefined ? new Response(null, { status: 204 }) : Response.json(value)
      if (method === 'HEAD')
        return new Response(null, { status: response.status, headers: response.headers })
      return response
    }
    catch (error) {
      console.error(`[stx] API error for ${method} ${pattern}:`, error)
      return Response.json({ error: 'Internal Server Error' }, { status: 500 })
    }
  }
}

export function productionApiDispatcher(outputDir: string, routes: ServerApiRoute[]): (request: Request) => Promise<Response | null> {
  return createApiDispatcher(routes, async route => (await import(pathToFileURL(path.resolve(outputDir, route.filePath)).href)).default)
}

/** Development rescans and bundles per API request, including transitive edits. No stale module cache. */
export async function createServerApi(root: string, enabled: boolean | ServerApiOptions | undefined): Promise<(request: Request) => Promise<Response | null>> {
  if (!enabled) return async () => null
  const options = enabled === true ? {} : enabled
  const initial = discoverServerApi(root, options)
  await generateApiTypes(root, initial)
  return async (request) => {
    if (!new URL(request.url).pathname.match(/^\/api(?:\/|$)/)) return null
    try {
      const routes = discoverServerApi(root, options)
      await generateApiTypes(root, routes)
      const { loadStxConfig } = await import('./config')
      const runtimeConfig = resolveRuntimeConfig((await loadStxConfig(root)).runtimeConfig)
      return await withRuntimeConfig(runtimeConfig, () => createApiDispatcher(routes, async (route) => {
        const build = await Bun.build({ entrypoints: [route.filePath], target: 'bun', format: 'esm', splitting: false })
        if (!build.success) throw new Error(build.logs.join('\n'))
        const output = build.outputs.find(file => file.kind === 'entry-point')
        if (!output || build.outputs.length !== 1) throw new Error(`Unsupported API bundle output: ${route.filePath}`)
        // Content-addressed import: changed helper contents produce a new module,
        // unchanged requests share one. No generated code is served to browsers.
        return (await import(`data:text/javascript;base64,${Buffer.from(await output.text()).toString('base64')}`)).default
      })(request))
    }
    catch (error) {
      console.error('[stx] API discovery failed:', error)
      return Response.json({ error: 'API discovery failed; check the server log' }, { status: 500 })
    }
  }
}

/** Never expose endpoint source through a server that also serves the project root. */
export function isServerApiSource(filePath: string, root: string, enabled: boolean | ServerApiOptions | undefined): boolean {
  const privateName = /^(?:(?:stx|ui)\.config\.[cm]?[jt]s|runtime-config-(?:server|loader)\.[cm]?[jt]s)$/
  if (privateName.test(path.basename(filePath))) return true
  try { if (privateName.test(path.basename(fs.realpathSync(filePath)))) return true }
  catch {}
  if (discoveredSources.has(path.resolve(filePath))) return true
  if (!enabled) return false
  const apiDir = path.resolve(root, typeof enabled === 'object' ? enabled.dir ?? 'server/api' : 'server/api')
  const canonical = (value: string): string => {
    try { return fs.realpathSync(value) }
    catch { return path.resolve(value) }
  }
  const file = canonical(filePath)
  return [apiDir, path.resolve(root, 'server'), path.resolve(root, '.output/server')].some((value) => {
    const directory = canonical(value)
    return file === directory || file.startsWith(`${directory}${path.sep}`)
  })
}
