name: Daily Dependency Updates

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering
    inputs:
      strategy:
        description: 'Update strategy'
        required: false
        default: 'patch'
        type: choice
        options:
          - all
          - major
          - minor
          - patch
      dry_run:
        description: 'Dry run (preview only)'
        required: false
        default: false
        type: boolean

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: read
  checks: read
  statuses: read

jobs:
  dependency-updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build buddy-bot
        run: bun run build

      - name: Run Buddy dependency updates
        run: |
          STRATEGY="${{ github.event.inputs.strategy || 'patch' }}"
          DRY_RUN="${{ github.event.inputs.dry_run || 'false' }}"

          if [ "$DRY_RUN" = "true" ]; then
            ./buddy update --strategy "$STRATEGY" --dry-run --verbose
          else
            ./buddy update --strategy "$STRATEGY" --verbose
          fi

      - name: Auto-merge updates
        if: ${{ true }}
        run: |
          echo "Auto-merge is enabled for this workflow"

          # Check if conditions are met for auto-merge
          STRATEGY="${{ github.event.inputs.strategy || 'patch' }}"
          AUTO_MERGE_STRATEGY="squash"

          echo "Update strategy: $STRATEGY"
          echo "Auto-merge strategy: $AUTO_MERGE_STRATEGY"

          # Enable auto-merge for created PRs
          # This will be implemented when the PR creation logic is fully integrated
          # For now, this step serves as a placeholder and configuration validation

          if [ "$STRATEGY" = "patch" ]; then
            echo "✅ Patch updates are eligible for auto-merge"
          else
            echo "ℹ️ Only patch updates are auto-merged by default"
          fi
